name: syncfusion_examples
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.0
  path_provider: ^2.0.1
  path_provider_foundation: ^2.1.0
  desktop_window: 0.4.0
  intl: ^0.18.0

  syncfusion_localizations: ^25.1.35
  syncfusion_flutter_datagrid_export: ^25.1.35
  syncfusion_flutter_calendar: ^25.1.35
  syncfusion_flutter_datepicker: ^25.1.35
  syncfusion_flutter_charts: ^25.1.35
  syncfusion_flutter_gauges: ^25.1.35
  syncfusion_flutter_sliders: ^25.1.35
  syncfusion_flutter_pdf: ^25.1.35
  syncfusion_flutter_barcodes: ^25.1.35
  syncfusion_officechart: ^25.1.35
  syncfusion_flutter_maps: ^25.1.35
  syncfusion_flutter_signaturepad: ^25.1.35
  syncfusion_flutter_pdfviewer: ^25.1.35
  syncfusion_flutter_treemap: ^25.1.35

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - images/pdf_viewer/
    - assets/pdf/
    - lib/sample_details.json
    - assets/world_map.json
    - assets/africa.json
    - assets/europe.json
    - assets/germany.json
    - assets/india.json
    - assets/usa.json
    - assets/south_america.json
    - assets/australia.json
    - assets/maps_brazil_boundary.json
    - assets/maps_uk_boundary.json
    - assets/maps_france_boundary.json
    - assets/river.json
    - assets/london_to_british.json
    - assets/london_to_chessington.json
    - assets/london_to_hampton_court_palace.json
    - assets/london_to_twickenham_stadium.json
    - assets/london_to_windsor_castle.json
    - assets/product_data.json
    - assets/chart_data.json
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
